### ISSUE TITLE
After upgrading from 8.5 to 9.3.1, there was an issue with the installation of the plugin package.

### ISSUE THREAD

**Issue by Nioy** [getinsomnia/insomnia#7662]
### Expected Behavior

![image](https://github.com/Kong/insomnia/assets/13707298/a48583aa-990d-4ec1-919c-fac769e3ab4e)

### Actual Behavior

Error: Cannot find module 'nedb'
Require stack:
- /Applications/Insomnia.app/Contents/Resources/app.asar/index.html
    at Module._resolveFilename (node:internal/modules/cjs/loader:1151:15)
    at a._resolveFilename (node:electron/js2c/renderer_init:2:2669)
    at Module._load (node:internal/modules/cjs/loader:992:27)
    at c._load (node:electron/js2c/node_init:2:13672)
    at s._load (node:electron/js2c/renderer_init:2:31018)
    at Module.require (node:internal/modules/cjs/loader:1242:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (/Users/njy/Library/Application Support/Insomnia/plugins/insomnia-plugin-request-navigator/index.js:3193:19)
    at Object.<anonymous> (/Users/njy/Library/Application Support/Insomnia/plugins/insomnia-plugin-request-navigator/index.js:3765:3)
    at Module._compile (node:internal/modules/cjs/loader:1391:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1451:10)
    at Module.load (node:internal/modules/cjs/loader:1214:32)
    at Module._load (node:internal/modules/cjs/loader:1030:12)
    at c._load (node:electron/js2c/node_init:2:13672)
    at s._load (node:electron/js2c/renderer_init:2:31018)
    at Module.require (node:internal/modules/cjs/loader:1242:19)
    at require (node:internal/modules/helpers:176:18)
    at YY (file:///Applications/Insomnia.app/Contents/Resources/app.asar/mainWindow-DhtvoTeM.js:82:7674)
    at async EM (file:///Applications/Insomnia.app/Contents/Resources/app.asar/mainWindow-DhtvoTeM.js:82:8482)
    at async l (file:///Applications/Insomnia.app/Contents/Resources/app.asar/mainWindow-DhtvoTeM.js:1481:34118)

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Insomnia Version

9.3.1

### What operating system are you using?

macOS

### Operating System Version

macos 14.5

### Installation method

Automatic Update

### Last Known Working Insomnia version

8.5

**Comment by jackkav** [comment]
nedb is deprecated we use `@seald-io/nedb` now, please instruct the plugin author to upgrade this package.
