### ISSUE TITLE
Complex XQuery Expression not working in Insomnia 8.4.5

### ISSUE THREAD

**Issue by dhaeb** [getinsomnia/insomnia#6898]
### Expected Behavior

My XPath Expression: `substring-before(substring-after(/, 'token='),'&')`which worked in older versions should work again:
<img width="751" alt="image" src="https://github.com/Kong/insomnia/assets/3354824/d4b002f4-95d6-4a46-9f49-18fe50b616e5">

### Actual Behavior

TypeError: H.filter is not a function 

is the output and the Token from the other request is not extracted. 

### Reproduction Steps

1) Create a request which you can reference in a TAG. It should have a body. 
2) In the TAG, make sure to execute a nested XQuery expression like this: `substring-before(substring-after(/, 'token='),'&')`
3) Then, you should get the similar type error then me.

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

<img width="284" alt="image" src="https://github.com/Kong/insomnia/assets/3354824/d83172b4-7905-4e5d-9a23-d2c443b3ff19">

### Insomnia Version

8.4.5

### What operating system are you using?

macOS

### Operating System Version

13.0 (22A380)

### Installation method

Download over Web Interface / Github

### Last Known Working Insomnia version

2023.5.2
