### ISSUE TITLE
oAuth 2 Mate Not Working in Insomnia 8.6.0

### ISSUE THREAD

**Issue by smiller0924** [getinsomnia/insomnia#7019]
### Expected Behavior

My oAuth 2 Mate is throwing an error where I try to access the plugin.   The Plugins are not working correctly

### Actual Behavior

When I click the Plugins I get the following error: Failed to load plugin insomnia-plugin-oa2-mate

Here is what is showing in the Stack Trace:
Error: Cannot find module 'nedb'
Require stack:
- C:\Users\sm623\AppData\Local\insomnia\app-8.6.0\resources\app.asar\index.html
    at Module._resolveFilename (node:internal/modules/cjs/loader:1084:15)
    at o._resolveFilename (node:electron/js2c/renderer_init:2:3225)
    at Module._load (node:internal/modules/cjs/loader:929:27)
    at l._load (node:electron/js2c/asar_bundle:2:13642)
    at o._load (node:electron/js2c/renderer_init:2:2455)
    at Module.require (node:internal/modules/cjs/loader:1150:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (C:\Users\sm623\AppData\Roaming\Insomnia\plugins\insomnia-plugin-oa2-mate\index.js:79:19)
    at Object.<anonymous> (C:\Users\sm623\AppData\Roaming\Insomnia\plugins\insomnia-plugin-oa2-mate\index.js:181:3)
    at Module._compile (node:internal/modules/cjs/loader:1271:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1326:10)
    at Module.load (node:internal/modules/cjs/loader:1126:32)
    at Module._load (node:internal/modules/cjs/loader:967:12)
    at l._load (node:electron/js2c/asar_bundle:2:13642)
    at o._load (node:electron/js2c/renderer_init:2:2455)
    at Module.require (node:internal/modules/cjs/loader:1150:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at uG (file:///C:/Users/sm623/AppData/Local/insomnia/app-8.6.0/resources/app.asar/index-0fe701a5.js:81:7484)
    at Sk (file:///C:/Users/sm623/AppData/Local/insomnia/app-8.6.0/resources/app.asar/index-0fe701a5.js:81:8221)
    at async u (file:///C:/Users/sm623/AppData/Local/insomnia/app-8.6.0/resources/app.asar/index-0fe701a5.js:1560:17437)

### Reproduction Steps

1. Click Application
2. Click Preferences
3. Click Plugins
4. Get error, "Failed to load plugin insomnia-plugin-oa2-mate"

- 
![image](https://github.com/Kong/insomnia/assets/108164566/3b74655e-55f6-4c37-ad23-b088e8a5973f)

5. Click Stack Trace
`Error: Cannot find module 'nedb'
Require stack:
- C:\Users\sm623\AppData\Local\insomnia\app-8.6.0\resources\app.asar\index.html
    at Module._resolveFilename (node:internal/modules/cjs/loader:1084:15)
    at o._resolveFilename (node:electron/js2c/renderer_init:2:3225)
    at Module._load (node:internal/modules/cjs/loader:929:27)
    at l._load (node:electron/js2c/asar_bundle:2:13642)
    at o._load (node:electron/js2c/renderer_init:2:2455)
    at Module.require (node:internal/modules/cjs/loader:1150:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (C:\Users\sm623\AppData\Roaming\Insomnia\plugins\insomnia-plugin-oa2-mate\index.js:79:19)
    at Object.<anonymous> (C:\Users\sm623\AppData\Roaming\Insomnia\plugins\insomnia-plugin-oa2-mate\index.js:181:3)
    at Module._compile (node:internal/modules/cjs/loader:1271:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1326:10)
    at Module.load (node:internal/modules/cjs/loader:1126:32)
    at Module._load (node:internal/modules/cjs/loader:967:12)
    at l._load (node:electron/js2c/asar_bundle:2:13642)
    at o._load (node:electron/js2c/renderer_init:2:2455)
    at Module.require (node:internal/modules/cjs/loader:1150:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at uG (file:///C:/Users/sm623/AppData/Local/insomnia/app-8.6.0/resources/app.asar/index-0fe701a5.js:81:7484)
    at Sk (file:///C:/Users/sm623/AppData/Local/insomnia/app-8.6.0/resources/app.asar/index-0fe701a5.js:81:8221)
    at async u (file:///C:/Users/sm623/AppData/Local/insomnia/app-8.6.0/resources/app.asar/index-0fe701a5.js:1560:17437)`

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

The only way to clear it is to remove the oAuth 2 Mate.  As a result I have to change my Insomnia in the method it captures the oAuth Token.  How do we make this work?

### Insomnia Version

8.6.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### Installation method

Automatic upgrade

### Last Known Working Insomnia version

8.5.0

**Comment by jackkav** [comment]
Insomnia is now using a fork of nedb, https://www.npmjs.com/package/@seald-io/nedb so updating the `insomnia-plugin-oa2-mate` to point at `@seald-io/nedb` should correct this.

**Comment by smiller0924** [comment]
Where exactly do I change where the "insomnia-plugin-oa2-mate" points to "@seald-io/nedb"?

**Comment by smiller0924** [comment]
Never mind.  I figured it out.  I went into index.js.  Then changed: "var NeDb = window.require("nedb"); " to "var NeDb = window.require("@seald-io/nedb");"

**Comment by briantully** [comment]
Does this mean everyone needs to find and update index.js to point to the correct nedb? I'm getting this error with the latest version (10.0) of Insomnia on macOS:

```
Error: Cannot find module 'nedb'
Require stack:
- /Applications/Insomnia.app/Contents/Resources/app.asar/index.html
    at Module._resolveFilename (node:internal/modules/cjs/loader:1152:15)
    at a._resolveFilename (node:electron/js2c/renderer_init:2:2669)
    at Module._load (node:internal/modules/cjs/loader:993:27)
    at c._load (node:electron/js2c/node_init:2:17025)
    at s._load (node:electron/js2c/renderer_init:2:31018)
    at Module.require (node:internal/modules/cjs/loader:1240:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/Users/brian.tully/Library/Application Support/Insomnia/plugins/insomnia-plugin-request-navigator/index.js:3202:19)
    at Object.<anonymous> (/Users/brian.tully/Library/Application Support/Insomnia/plugins/insomnia-plugin-request-navigator/index.js:3774:3)
    at Module._compile (node:internal/modules/cjs/loader:1373:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1432:10)
    at Module.load (node:internal/modules/cjs/loader:1215:32)
    at Module._load (node:internal/modules/cjs/loader:1031:12)
    at c._load (node:electron/js2c/node_init:2:17025)
    at s._load (node:electron/js2c/renderer_init:2:31018)
    at Module.require (node:internal/modules/cjs/loader:1240:19)
    at require (node:internal/modules/helpers:179:18)
    at _traversePluginPath (file:///Applications/Insomnia.app/Contents/Resources/app.asar/mainWindow-DV0jvs_A.js:82:7926)
    at async getPlugins (file:///Applications/Insomnia.app/Contents/Resources/app.asar/mainWindow-DV0jvs_A.js:82:8922)
    at async st (file:///Applications/Insomnia.app/Contents/Resources/app.asar/mainWindow-DV0jvs_A.js:1444:63022)
```

Where do i find "index.js" and why is this bug closed?

**Comment by eminach** [comment]
@briantully the index.js located under AppData\Roaming\Insomnia\plugins\{pugin_name} folder
